/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package devlop_apk_ban;

import devlop_apk_ban.AdminBarang;
import devlop_apk_ban.Barang;


import java.awt.CardLayout;
import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.Element;

/**
 *
 * @author acer
 */
public class Aplikasi extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Aplikasi() {
    initComponents();
        jpisi.setLayout(new CardLayout());
    jpisi.add(jphome, "home");
    jpisi.add(jpkategoribox, "kategoribox");
    jpisi.add(jpcekout, "cekout");

    // Fix for btnban1 (index 0)
    if (!AdminBarang.getSemuaBarang().isEmpty()) {
        Barang b = AdminBarang.getSemuaBarang().get(0);
        btnban1.setText(b.nama);
    } else {
        btnban1.setText("Kosong");
    }

    // Fix for btnban2 (index 1)
    if (AdminBarang.getSemuaBarang().size() > 1) { // Check size > 1
        Barang b = AdminBarang.getSemuaBarang().get(1);
        btnban2.setText(b.nama);
    } else {
        btnban2.setText("Kosong");
    }

    // Fix for btnban3 (index 2)
    if (AdminBarang.getSemuaBarang().size() > 2) { // Check size > 2
        Barang b = AdminBarang.getSemuaBarang().get(2);
        btnban3.setText(b.nama);
    } else {
        btnban3.setText("Kosong");
    }

    // Fix for btnban4 (index 3)
    if (AdminBarang.getSemuaBarang().size() > 3) { // Check size > 3
        Barang b = AdminBarang.getSemuaBarang().get(3);
        btnban4.setText(b.nama);
    } else {
        btnban4.setText("Kosong");
    }

    GambarManager.tampilkanSemuaGambarKeLabel(new JLabel[]{lbimg1, lbimg2, lbimg3, lbimg4});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcprofile = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        btncs = new javax.swing.JButton();
        btnnotif = new javax.swing.JButton();
        btnaccount = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jspisi = new javax.swing.JScrollPane();
        jpisi = new javax.swing.JPanel();
        jphome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbimg1 = new javax.swing.JLabel();
        lbimg2 = new javax.swing.JLabel();
        lbimg4 = new javax.swing.JLabel();
        lbimg3 = new javax.swing.JLabel();
        btnban1 = new javax.swing.JButton();
        btnban2 = new javax.swing.JButton();
        btnban4 = new javax.swing.JButton();
        btnban3 = new javax.swing.JButton();
        jpkategoribox = new javax.swing.JPanel();
        jpbox1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        cbk1 = new javax.swing.JCheckBox();
        cbk2 = new javax.swing.JCheckBox();
        cbk3 = new javax.swing.JCheckBox();
        cbk4 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbimg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jpcekout = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaalamat = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btncs.setBackground(new java.awt.Color(0, 0, 0));
        btncs.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Downloads\\jawa\\JavaAsset\\CS.png")); // NOI18N
        btncs.setText("CS");
        btncs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncsActionPerformed(evt);
            }
        });

        btnnotif.setBackground(new java.awt.Color(0, 0, 0));
        btnnotif.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\com.mycompany_APK_Jual_ban_test\\src\\main\\java\\JavaAsset\\notif_1.png")); // NOI18N
        btnnotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnotifActionPerformed(evt);
            }
        });

        btnaccount.setBackground(new java.awt.Color(0, 0, 0));
        btnaccount.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\com.mycompany_APK_Jual_ban_test\\src\\main\\java\\JavaAsset\\Profile.png")); // NOI18N
        btnaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccountActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jspisi.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspisi.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jpisi.setLayout(new java.awt.CardLayout());

        jphome.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\com.mycompany_APK_Jual_ban_test\\src\\main\\java\\devlop_apk_ban\\banner.png")); // NOI18N

        lbimg1.setBackground(new java.awt.Color(255, 255, 255));
        lbimg1.setForeground(new java.awt.Color(255, 255, 255));
        lbimg1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbimg1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lbimg2.setBackground(new java.awt.Color(255, 255, 255));
        lbimg2.setForeground(new java.awt.Color(255, 255, 255));
        lbimg2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbimg2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lbimg4.setBackground(new java.awt.Color(255, 255, 255));
        lbimg4.setForeground(new java.awt.Color(255, 255, 255));
        lbimg4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbimg4AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lbimg3.setBackground(new java.awt.Color(255, 255, 255));
        lbimg3.setForeground(new java.awt.Color(255, 255, 255));

        btnban1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban1ActionPerformed(evt);
            }
        });

        btnban2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban2ActionPerformed(evt);
            }
        });

        btnban4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban4ActionPerformed(evt);
            }
        });

        btnban3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnban3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jphomeLayout = new javax.swing.GroupLayout(jphome);
        jphome.setLayout(jphomeLayout);
        jphomeLayout.setHorizontalGroup(
            jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
            .addGroup(jphomeLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jphomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnban1)
                        .addGap(61, 61, 61))
                    .addGroup(jphomeLayout.createSequentialGroup()
                        .addComponent(lbimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbimg2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jphomeLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnban2)))
                .addGap(18, 18, 18)
                .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jphomeLayout.createSequentialGroup()
                        .addComponent(lbimg3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbimg4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jphomeLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnban3)
                        .addGap(106, 106, 106)
                        .addComponent(btnban4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jphomeLayout.setVerticalGroup(
            jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jphomeLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbimg3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbimg4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbimg2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnban3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnban4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnban2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnban1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1554, Short.MAX_VALUE))
        );

        jpisi.add(jphome, "card2");

        jpkategoribox.setBackground(new java.awt.Color(255, 255, 255));

        jpbox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel25.setText("Kategori Pilihan");

        cbk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbk1ActionPerformed(evt);
            }
        });

        cbk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbk2ActionPerformed(evt);
            }
        });

        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton4.setText("Beli");

        jLabel6.setText("Jumlah");

        lbimg.setText("Gambar barang");

        jLabel8.setText("Nama barang");

        jButton3.setText("+");

        jButton9.setText("-");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setText("Deskripsi");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jpbox1Layout = new javax.swing.GroupLayout(jpbox1);
        jpbox1.setLayout(jpbox1Layout);
        jpbox1Layout.setHorizontalGroup(
            jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbox1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpbox1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbox1Layout.createSequentialGroup()
                        .addGroup(jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpbox1Layout.createSequentialGroup()
                                .addComponent(lbimg, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpbox1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbk2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbk1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbk3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbk4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(65, 65, 65))
                                    .addGroup(jpbox1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jpbox1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpbox1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpbox1Layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31))
        );
        jpbox1Layout.setVerticalGroup(
            jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbox1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel25)
                .addGroup(jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpbox1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lbimg, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpbox1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jpbox1Layout.createSequentialGroup()
                                .addComponent(cbk1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbk2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbk3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbk4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addGroup(jpbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jButton3)
                                    .addComponent(jButton9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpkategoriboxLayout = new javax.swing.GroupLayout(jpkategoribox);
        jpkategoribox.setLayout(jpkategoriboxLayout);
        jpkategoriboxLayout.setHorizontalGroup(
            jpkategoriboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpkategoriboxLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jpbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
        );
        jpkategoriboxLayout.setVerticalGroup(
            jpkategoriboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpkategoriboxLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jpbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1550, Short.MAX_VALUE))
        );

        jpisi.add(jpkategoribox, "card5");

        jpcekout.setBackground(new java.awt.Color(0, 0, 0));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Check Out");

        jLabel29.setText("Transfer");

        jLabel30.setText("No rek ************************");

        jButton1.setText("Konfimasi Pembayaran");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Upload Bukti pembayaran");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel29)
                .addGap(21, 21, 21)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(71, 71, 71))
        );

        jLabel24.setText("total barang");

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel35.setText("Harga barang");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel36.setText("Nama barang");

        jLabel3.setText("Ukuran");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(5, 5, 5)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jtaalamat.setColumns(20);
        jtaalamat.setRows(5);
        jtaalamat.setText("Nama:\nNo.HP:\nAlamat:\n");
        jtaalamat.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jtaalamatAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jtaalamat);

        javax.swing.GroupLayout jpcekoutLayout = new javax.swing.GroupLayout(jpcekout);
        jpcekout.setLayout(jpcekoutLayout);
        jpcekoutLayout.setHorizontalGroup(
            jpcekoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcekoutLayout.createSequentialGroup()
                .addGroup(jpcekoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpcekoutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpcekoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpcekoutLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jpcekoutLayout.setVerticalGroup(
            jpcekoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcekoutLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpcekoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpcekoutLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1593, Short.MAX_VALUE))
        );

        jpisi.add(jpcekout, "card7");

        jspisi.setViewportView(jpisi);

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\com.mycompany_APK_Jual_ban_test\\src\\main\\java\\JavaAsset\\search.png")); // NOI18N
        jButton5.setText("jButton5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jspisi, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btncs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnnotif)
                        .addGap(18, 18, 18)
                        .addComponent(btnaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnotif)
                    .addComponent(btnaccount)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspisi, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void bukaKategoriBerdasarkanIndex(int index) {
    CardLayout cl = (CardLayout) jpisi.getLayout();
    cl.show(jpisi, "kategoribox"); // pindah panel
        JLabel lbimgkategori = null;

    GambarManager.tampilkanGambarKeLabelBerdasarkanIndex(lbimgkategori, index);
}

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void btncsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncsActionPerformed
     btncs.setContentAreaFilled(false); // hilangkan isi background
    btncs.setBorderPainted(false);     // hilangkan border
    btncs.setFocusPainted(false);      // hilangkan efek fokus
    btncs.setOpaque(false);            // supaya benar-benar transparan

        
        CardLayout cl = (CardLayout)(jpisi.getLayout());
    cl.show(jpisi, "cs");     // TODO add your handling code here:
    }//GEN-LAST:event_btncsActionPerformed

    private void btnaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccountActionPerformed
    CardLayout cl = (CardLayout)(jpisi.getLayout());
    cl.show(jpisi, "account");
        // Buka form admintest
    admintest at = new admintest();
    at.setVisible(true);
    at.pack();
    at.setLocationRelativeTo(null);
    at.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    
    // Tutup jendela saat ini
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnaccountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean filterApplied = false; 
    private void jtaalamatAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jtaalamatAncestorAdded

    }//GEN-LAST:event_jtaalamatAncestorAdded

    private void btnnotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnotifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnotifActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void lbimg1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbimg1AncestorAdded
                                 
    //GambarManager.tampilkanGambarKeLabel(lbimg1);            // TODO add your handling code here:
    }//GEN-LAST:event_lbimg1AncestorAdded

    private void lbimg2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbimg2AncestorAdded
        //GambarManager.tampilkanGambarKeLabel(lbimg2);          // TODO add your handling code here:
    }//GEN-LAST:event_lbimg2AncestorAdded

    private void lbimg4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbimg4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbimg4AncestorAdded

    private void btnban1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban1ActionPerformed
        
                                         
    // Get the product data
    Barang b = AdminBarang.getSemuaBarang().get(0);
    
    // Update jpbox1 components
    jLabel8.setText(b.getNama());          // Product name
    jTextArea1.setText(b.getDeskripsi());  // Product description
    jTextField2.setText("0");              // Reset quantity
    
    // Load and display the product image
    String path = "images/" + b.getGambar(); // Adjust path as needed
    ImageIcon icon = new ImageIcon(path);
    Image img = icon.getImage().getScaledInstance(lbimg.getWidth(), lbimg.getHeight(), Image.SCALE_SMOOTH);
    lbimg.setIcon(new ImageIcon(img));
    lbimg.setText(""); // Clear placeholder text
    
    // Switch to the kategoribox panel
    CardLayout cl = (CardLayout) jpisi.getLayout();
    cl.show(jpisi, "kategoribox");
    
File imgFile = new File(path);
if (!imgFile.exists()) {
    lbimg.setIcon(null);
    lbimg.setText("Gambar tidak ditemukan");
    System.err.println("Image not found: " + path);
}
    }//GEN-LAST:event_btnban1ActionPerformed

    private void btnban2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban2ActionPerformed
    Barang b = AdminBarang.getSemuaBarang().get(1);
    btnban2.setText(b.getNama());
    
    
        // Ganti ke panel kategori
    CardLayout cl = (CardLayout) jpisi.getLayout();
    cl.show(jpisi, "kategoribox");

    String path = "images/timotod.jpg";
    File imgFile = new File(path);
    if (imgFile.exists()) {
        System.out.println("Menampilkan langsung gambar: " + path);
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage().getScaledInstance(lbimg2.getWidth(), lbimg2.getHeight(), Image.SCALE_SMOOTH);
        lbimg2.setIcon(new ImageIcon(img));
        lbimg2.setText("");
    } else {
        lbimg2.setIcon(null);
        lbimg2.setText("Gambar tidak ditemukan");
    }


 // TODO add your handling code here:
    }//GEN-LAST:event_btnban2ActionPerformed

    private void cbk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbk2ActionPerformed

    private void cbk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbk1ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_cbk1ActionPerformed

    private void btnban3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban3ActionPerformed
    Barang b = AdminBarang.getSemuaBarang().get(2);
    btnban3.setText(b.getNama());
    
    
        // Ganti ke panel kategori
    CardLayout cl = (CardLayout) jpisi.getLayout();
    cl.show(jpisi, "kategoribox");

    String path = "images/timotod.jpg";
    File imgFile = new File(path);
    if (imgFile.exists()) {
        System.out.println("Menampilkan langsung gambar: " + path);
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage().getScaledInstance(lbimg3.getWidth(), lbimg3.getHeight(), Image.SCALE_SMOOTH);
        lbimg3.setIcon(new ImageIcon(img));
        lbimg3.setText("");
    } else {
        lbimg3.setIcon(null);
        lbimg3.setText("Gambar tidak ditemukan");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnban3ActionPerformed

    private void btnban4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnban4ActionPerformed
        Barang b = AdminBarang.getSemuaBarang().get(3);
        btnban4.setText(b.getNama());

        // Ganti ke panel kategori
        CardLayout cl = (CardLayout) jpisi.getLayout();
        cl.show(jpisi, "kategoribox");

        String path = "images/timotod.jpg";
        File imgFile = new File(path);
        if (imgFile.exists()) {
            System.out.println("Menampilkan langsung gambar: " + path);
            ImageIcon icon = new ImageIcon(path);
            Image img = icon.getImage().getScaledInstance(lbimg4.getWidth(), lbimg4.getHeight(), Image.SCALE_SMOOTH);
            lbimg4.setIcon(new ImageIcon(img));
            lbimg4.setText("");
        } else {
            lbimg4.setIcon(null);
            lbimg4.setText("Gambar tidak ditemukan");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnban4ActionPerformed
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
    ArrayList<Barang> daftar = AdminBarang.getSemuaBarang();

    // Contoh jika ada minimal 1 barang
    if (daftar.size() > 0) {
        btnban1.setText(daftar.get(0).getNama());
    }
    if (daftar.size() > 1) {
        btnban2.setText(daftar.get(1).getNama());
    }
    if (daftar.size() > 2) {
        btnban3.setText(daftar.get(2).getNama());
    }
    if (daftar.size() > 3) {
        btnban4.setText(daftar.get(3).getNama());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaccount;
    private javax.swing.JButton btnban1;
    private javax.swing.JButton btnban2;
    private javax.swing.JButton btnban3;
    private javax.swing.JButton btnban4;
    private javax.swing.JButton btncs;
    private javax.swing.JButton btnnotif;
    private javax.swing.JCheckBox cbk1;
    private javax.swing.JCheckBox cbk2;
    private javax.swing.JCheckBox cbk3;
    private javax.swing.JCheckBox cbk4;
    private javax.swing.JFileChooser fcprofile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel jpbox1;
    private javax.swing.JPanel jpcekout;
    private javax.swing.JPanel jphome;
    private javax.swing.JPanel jpisi;
    private javax.swing.JPanel jpkategoribox;
    private javax.swing.JScrollPane jspisi;
    private javax.swing.JTextArea jtaalamat;
    private javax.swing.JLabel lbimg;
    private javax.swing.JLabel lbimg1;
    private javax.swing.JLabel lbimg2;
    private javax.swing.JLabel lbimg3;
    private javax.swing.JLabel lbimg4;
    // End of variables declaration//GEN-END:variables

}
